# Generated by Django 6.0.6 on 2026-06-24 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('wellfound', 'WellFound'), ('internshala', 'Internshala'), ('unstop', 'Unstop'), ('comapny_website', 'Company Website'), ('referral', 'Referral'), ('cold_email', 'Cold Email'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('online_assessment', 'Online Assessment'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('ghosted', 'Ghosted')], default='saved', max_length=100)),
                ('job_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
