# Generated by Django 6.0.6 on 2026-06-26 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_applications_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='job_url',
            new_name='application_link',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='company_name',
            new_name='company',
        ),
        migrations.AddField(
            model_name='applications',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='applications',
            name='resume_version',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='applications',
            name='salary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applications',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('wellfound', 'WellFound'), ('internshala', 'Internshala'), ('unstop', 'Unstop'), ('company_website', 'Company Website'), ('referral', 'Referral'), ('cold_email', 'Cold Email'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('wishlist', 'Wishlist'), ('applied', 'Applied'), ('online_assessment', 'Online Assessment'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('ghosted', 'Ghosted'), ('closed', 'Closed')], default='wishlist', max_length=30),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('headline', models.CharField(default='Job Seeker Pro', max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('target_role', models.CharField(blank=True, max_length=150)),
                ('preferred_platforms', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
